version: "3.8"

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - ./content:/app/content
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./ejemplos:/app/ejemplos
      - ./layouts:/app/layouts